'''
Resoerved the room on days
'''


Choice1 = input("Print all days the rooms in Setai Hotel are Available? Y/N\n")
if Choice1 == "y":
    if Room1_Setai_Hotel['Sunday'] == 1:print("Room1 is Available on Sunday")
    if Room1_Setai_Hotel['Monday'] == 1:print("Room1 is Available on Monday")
    if Room1_Setai_Hotel['Tuesday'] == 1:print("Room1 is Available on Tuesday")
    if Room1_Setai_Hotel['Wednesday'] == 1:print("Room1 is Available on Wednesday")
    if Room1_Setai_Hotel['Thursday'] == 1:print("Room1 is Available on Thursday")

    if Room2_Setai_Hotel['Sunday'] == 1:print("Room2 is Available on Sunday")
    if Room2_Setai_Hotel['Monday'] == 1:print("Room2 is Available on Monday")
    if Room2_Setai_Hotel['Tuesday'] == 1:print("Room2 is Available on Tuesday")
    if Room2_Setai_Hotel['Wednesday'] == 1:print("Room2 is Available on Wednesday")
    if Room2_Setai_Hotel['Thursday'] == 1:print("Room2 is Available on Thursday")

    if Room3_Setai_Hotel['Sunday'] == 1:print("Room3 is Available on Sunday")
    if Room3_Setai_Hotel['Monday'] == 1:print("Room3 is Available on Monday")
    if Room3_Setai_Hotel['Tuesday'] == 1:print("Room3 is Available on Tuesday")
    if Room3_Setai_Hotel['Wednesday'] == 1:print("Room3 is Available on Wednesday")
    if Room3_Setai_Hotel['Thursday'] == 1:print("Room3 is Available on Thursday")

    if Room4_Setai_Hotel['Sunday'] == 1:print("Room4 is Available on Sunday")
    if Room4_Setai_Hotel['Monday'] == 1:print("Room4 is Available on Monday")
    if Room4_Setai_Hotel['Tuesday'] == 1:print("Room4 is Available on Tuesday")
    if Room4_Setai_Hotel['Wednesday'] == 1:print("Room4 is Available on Wednesday")
    if Room4_Setai_Hotel['Thursday'] == 1:print("Room4 is Available on Thursday")


Choice1 = input("Print all days the rooms in Iris Hotel are Available? Y/N\n")
if Choice1 == "y":
    if Room1_Iris_Hotel['Sunday'] == 1: print("Room1 is Available on Sunday")
    if Room1_Iris_Hotel['Monday'] == 1: print("Room1 is Available on Monday")
    if Room1_Iris_Hotel['Tuesday'] == 1: print("Room1 is Available on Tuesday")
    if Room1_Iris_Hotel['Wednesday'] == 1: print("Room1 is Available on Wednesday")
    if Room1_Iris_Hotel['Thursday'] == 1: print("Room1 is Available on Thursday")

    if Room2_Iris_Hotel['Sunday'] == 1: print("Room2 is Available on Sunday")
    if Room2_Iris_Hotel['Monday'] == 1: print("Room2 is Available on Monday")
    if Room2_Iris_Hotel['Tuesday'] == 1: print("Room2 is Available on Tuesday")
    if Room2_Iris_Hotel['Wednesday'] == 1: print("Room2 is Available on Wednesday")
    if Room2_Iris_Hotel['Thursday'] == 1: print("Room2 is Available on Thursday")

    if Room3_Iris_Hotel['Sunday'] == 1: print("Room3 is Available on Sunday")
    if Room3_Iris_Hotel['Monday'] == 1: print("Room3 is Available on Monday")
    if Room3_Iris_Hotel['Tuesday'] == 1: print("Room3 is Available on Tuesday")
    if Room3_Iris_Hotel['Wednesday'] == 1: print("Room3 is Available on Wednesday")
    if Room3_Iris_Hotel['Thursday'] == 1: print("Room3 is Available on Thursday")

    if Room4_Iris_Hotel['Sunday'] == 1: print("Room4 is Available on Sunday")
    if Room4_Iris_Hotel['Monday'] == 1: print("Room4 is Available on Monday")
    if Room4_Iris_Hotel['Tuesday'] == 1: print("Room4 is Available on Tuesday")
    if Room4_Iris_Hotel['Wednesday'] == 1: print("Room4 is Available on Wednesday")
    if Room4_Iris_Hotel['Thursday'] == 1: print("Room4 is Available on Thursday")


Reserve_Room1_Sunday_Setai = input("Do you want to Reserve Room1 This Sunday? Y/N\n").lower()
if Reserve_Room1_Sunday_Setai == "y":Room1_Setai_Hotel.update(Sunday = 1)
Reserve_Room1_Monday_Setai = input("Do you want to Reserve Room1 This Monday? Y/N\n").lower()
if Reserve_Room1_Monday_Setai == "y":Room1_Setai_Hotel.update(Monday = 1)
Reserve_Room1_Tuesday_Setai = input("Do you want to Reserve Room1 This Tuesday? Y/N\n").lower()
if Reserve_Room1_Tuesday_Setai == "y":Room1_Setai_Hotel.update(Tuesday = 1)
Reserve_Room1_Wednesday_Setai = input("Do you want to Reserve Room1 This Wednesday? Y/N\n").lower()
if Reserve_Room1_Wednesday_Setai == "y":Room1_Setai_Hotel.update(Wednesday = 1)
Reserve_Room1_Thursday_Setai = input("Do you want to Reserve Room1 This Thursday? Y/N\n").lower()
if Reserve_Room1_Thursday_Setai == "y":Room1_Setai_Hotel.update(Thursday = 1)

Reserve_Room2_Sunday_Setai = input("Do you want to Reserve Room2 This Sunday? Y/N\n").lower()
if Reserve_Room2_Sunday_Setai == "y":Room2_Setai_Hotel.update(Sunday = 1)
Reserve_Room2_Monday_Setai = input("Do you want to Reserve Room2 This Monday? Y/N\n").lower()
if Reserve_Room2_Monday_Setai == "y":Room2_Setai_Hotel.update(Monday = 1)
Reserve_Room2_Tuesday_Setai = input("Do you want to Reserve Room2 This Tuesday? Y/N\n").lower()
if Reserve_Room2_Tuesday_Setai == "y":Room2_Setai_Hotel.update(Tuesday = 1)
Reserve_Room2_Wednesday_Setai = input("Do you want to Reserve Room2 This Wednesday? Y/N\n").lower()
if Reserve_Room2_Wednesday_Setai == "y":Room2_Setai_Hotel.update(Wednesday = 1)

Reserve_Room3_Sunday_Setai = input("Do you want to Reserve Room3 This Sunday? Y/N\n").lower()
if Reserve_Room3_Sunday_Setai == "y":Room3_Setai_Hotel.update(Sunday = 1)
Reserve_Room3_Monday_Setai = input("Do you want to Reserve Room3 This Monday? Y/N\n").lower()
if Reserve_Room3_Monday_Setai == "y":Room3_Setai_Hotel.update(Monday = 1)
Reserve_Room3_Tuesday_Setai = input("Do you want to Reserve Room3 This Tuesday? Y/N\n").lower()
if Reserve_Room3_Tuesday_Setai == "y":Room3_Setai_Hotel.update(Tuesday = 1)
Reserve_Room3_Wednesday_Setai = input("Do you want to Reserve Room3 This Wednesday? Y/N\n").lower()
if Reserve_Room3_Wednesday_Setai == "y":Room3_Setai_Hotel.update(Wednesday = 1)
Reserve_Room3_Thursday_Setai = input("Do you want to Reserve Room3 This Thursday? Y/N\n").lower()
if Reserve_Room3_Thursday_Setai == "y":Room3_Setai_Hotel.update(Thursday = 1)

Reserve_Room4_Sunday_Setai = input("Do you want to Reserve Room4 This Sunday? Y/N\n").lower()
if Reserve_Room4_Sunday_Setai == "y":Room4_Setai_Hotel.update(Sunday = 1)
Reserve_Room4_Monday_Setai = input("Do you want to Reserve Room4 This Monday? Y/N\n").lower()
if Reserve_Room4_Monday_Setai == "y":Room4_Setai_Hotel.update(Monday = 1)
Reserve_Room4_Tuesday_Setai = input("Do you want to Reserve Room4 This Tuesday? Y/N\n").lower()
if Reserve_Room4_Tuesday_Setai == "y":Room4_Setai_Hotel.update(Tuesday = 1)
Reserve_Room4_Wednesday_Setai = input("Do you want to Reserve Room4 This Wednesday? Y/N\n").lower()
if Reserve_Room4_Wednesday_Setai == "y":Room4_Setai_Hotel.update(Wednesday = 1)
Reserve_Room4_Thursday_Setai = input("Do you want to Reserve Room4 This Thursday? Y/N\n").lower()
if Reserve_Room4_Thursday_Setai == "y":Room4_Setai_Hotel.update(Thursday = 1)



Reserve_Room1_Sunday_Iris = input("Do you want to Reserve Room1 This Sunday? Y/N\n").lower()
if Reserve_Room1_Sunday_Iris == "y":Room1_Setai_Hotel.update(Sunday = 1)
Reserve_Room1_Monday_Iris = input("Do you want to Reserve Room1 This Monday? Y/N\n").lower()
if Reserve_Room1_Monday_Iris == "y":Room1_Setai_Hotel.update(Monday = 1)
Reserve_Room1_Tuesday_Iris = input("Do you want to Reserve Room1 This Tuesday? Y/N\n").lower()
if Reserve_Room1_Tuesday_Iris == "y":Room1_Setai_Hotel.update(Tuesday = 1)
Reserve_Room1_Wednesday_Iris = input("Do you want to Reserve Room1 This Wednesday? Y/N\n").lower()
if Reserve_Room1_Wednesday_Iris == "y":Room1_Setai_Hotel.update(Wednesday = 1)
Reserve_Room1_Thursday_Iris = input("Do you want to Reserve Room1 This Thursday? Y/N\n").lower()
if Reserve_Room1_Thursday_Iris == "y":Room1_Setai_Hotel.update(Thursday = 1)

Reserve_Room2_Sunday_Iris = input("Do you want to Reserve Room2 This Sunday? Y/N\n").lower()
if Reserve_Room2_Sunday_Iris == "y":Room2_Setai_Hotel.update(Sunday = 1)
Reserve_Room2_Monday_Iris = input("Do you want to Reserve Room2 This Monday? Y/N\n").lower()
if Reserve_Room2_Monday_Iris == "y":Room2_Setai_Hotel.update(Monday = 1)
Reserve_Room2_Tuesday_Iris = input("Do you want to Reserve Room2 This Tuesday? Y/N\n").lower()
if Reserve_Room2_Tuesday_Iris == "y":Room2_Setai_Hotel.update(Tuesday = 1)
Reserve_Room2_Wednesday_Iris = input("Do you want to Reserve Room2 This Wednesday? Y/N\n").lower()
if Reserve_Room2_Wednesday_Iris == "y":Room2_Setai_Hotel.update(Wednesday = 1)

Reserve_Room3_Sunday_Iris = input("Do you want to Reserve Room3 This Sunday? Y/N\n").lower()
if Reserve_Room3_Sunday_Iris == "y":Room3_Setai_Hotel.update(Sunday = 1)
Reserve_Room3_Monday_Iris = input("Do you want to Reserve Room3 This Monday? Y/N\n").lower()
if Reserve_Room3_Monday_Iris == "y":Room3_Setai_Hotel.update(Monday = 1)
Reserve_Room3_Tuesday_Iris = input("Do you want to Reserve Room3 This Tuesday? Y/N\n").lower()
if Reserve_Room3_Tuesday_Iris == "y":Room3_Setai_Hotel.update(Tuesday = 1)
Reserve_Room3_Wednesday_Iris = input("Do you want to Reserve Room3 This Wednesday? Y/N\n").lower()
if Reserve_Room3_Wednesday_Iris == "y":Room3_Setai_Hotel.update(Wednesday = 1)
Reserve_Room3_Thursday_Iris = input("Do you want to Reserve Room3 This Thursday? Y/N\n").lower()
if Reserve_Room3_Thursday_Iris == "y":Room3_Setai_Hotel.update(Thursday = 1)

Reserve_Room4_Sunday_Iris = input("Do you want to Reserve Room4 This Sunday? Y/N\n").lower()
if Reserve_Room4_Sunday_Iris == "y":Room4_Setai_Hotel.update(Sunday = 1)
Reserve_Room4_Monday_Iris = input("Do you want to Reserve Room4 This Monday? Y/N\n").lower()
if Reserve_Room4_Monday_Iris == "y":Room4_Setai_Hotel.update(Monday = 1)
Reserve_Room4_Tuesday_Iris = input("Do you want to Reserve Room4 This Tuesday? Y/N\n").lower()
if Reserve_Room4_Tuesday_Iris == "y":Room4_Setai_Hotel.update(Tuesday = 1)
Reserve_Room4_Wednesday_Iris = input("Do you want to Reserve Room4 This Wednesday? Y/N\n").lower()
if Reserve_Room4_Wednesday_Iris == "y":Room4_Setai_Hotel.update(Wednesday = 1)
Reserve_Room4_Thursday_Iris = input("Do you want to Reserve Room4 This Thursday? Y/N\n").lower()
if Reserve_Room4_Thursday_Iris == "y":Room4_Setai_Hotel.update(Thursday = 1)

